version: '3.3'
services:

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.monitoring.enabled=true
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic
    
  backend:
    environment:
      - ENV=development
      - HOST=0.0.0.0
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=aane
      - PUBLIC_URL=http://localhost:8000
      - WEBHOOK_SECRET=key
      - ACCESS_TOKEN_EXPIRES=30
      - REFRESH_TOKEN_EXPIRES=360
      - AUTH_SECRET_TOKEN=barhtah55$tHTf4%&hytyjed6jdy
      - JWT_ALGORITHM=HS256
      - ES_URL=http://elasticsearch:9200
    build: ./backend
    ports:
      - "8000:8000"
    volumes: ["./backend/:/app", "./sources/2020/:/app/sources"]
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  sources-loader-1:
    build: ./backend
    environment:
      - ES_URL=http://elasticsearch:9200
    volumes: ["./backend/:/app", "./sources/2020/:/app/sources"]
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: python3 sources_loader.py --cands --analise --partidos -uf RJ -uf CE
  
  sources-loader-2:
    build: ./backend
    environment:
      - ES_URL=http://elasticsearch:9200
    volumes: ["./backend/:/app", "./sources/2020/:/app/sources"]
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: python3 sources_loader.py --cands --analise --partidos -uf SP

  sources-loader-3:
    build: ./backend
    environment:
      - ES_URL=http://elasticsearch:9200
    volumes: ["./backend/:/app", "./sources/2020/:/app/sources"]
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: python3 sources_loader.py --cands --analise --partidos -uf SE -uf MA
    
  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  frontend:
    restart: always
    build: ./frontend
    stdin_open: true
    environment:
      - REACT_APP_API=http://acoisatabranca.com.br:8000
    volumes: ['./frontend:/app']

networks:
  elastic:
    driver: bridge

volumes:
  mongo-data:
  sources:
  esdata:
    driver: local
